---
- name: Gather the apt package facts
  package_facts:
    manager: auto
  no_log: "true"

- name: Check whether a package called hyper is installed
  debug:
    msg: "{{ ansible_facts.packages['hyper'] | length }} versions of hyper are installed!"
  when: "'hyper' in ansible_facts.packages"

# - name: Print the package facts
#   debug:
#     var: ansible_facts.packages['hyper']
#   when: "'hyper' in ansible_facts.packages"

- name: Set the version, assuming first package
  set_fact:
    hyper_installed_version: "{{ ansible_facts.packages['hyper'][0]['version'] }}"
  when: "'hyper' in ansible_facts.packages"

- name: Print the version, assuming first package
  debug:
    var: hyper_installed_version
  when: "'hyper' in ansible_facts.packages"

- name: Install hyper deb from github
  become: true
  apt:
    deb: >-
      {{ hyper_url }}/{{ hyper_version }}/hyper_{{ hyper_version }}_amd64.deb
  when: "'hyper' not in ansible_facts.packages or hyper_version not in hyper_installed_version"

- name: Register currently installed hyper extensions
  shell: hyper list
  register: installed_hyper_extensions
  changed_when: "false"
  ignore_errors: yes # GitHub CI issue, don't currently care, works locally

- name: Debug currently installed hyper extensions
  debug:
    var: installed_hyper_extensions.stdout_lines
  ignore_errors: yes # GitHub CI issue, don't currently care, works locally

- name: Install hyper extensions
  command: hyper i "{{ item }}"
  with_items: "{{ hyper_extensions }}"
  when: "item not in installed_hyper_extensions.stdout_lines"
  ignore_errors: yes # GitHub CI issue, don't currently care, works locally

# Managed with yadm in https://github.com/iancleary/dotfiles
# - name: Enable in .hyper.js template
#   template:
#     src: .hyper.js.j2
#     dest: ~/.hyper.js
#     mode: "0644"

## Decided not to do these, but didn't want to delete the code

# - name: Install Colorls Gem
#   include_tasks: install_colorls.yml

# - name: Download FiraCode
#   include_tasks: download_font.yml
