---
- name: Copy SD-WAN Portal License file to the Docker hosts
  copy:
    src={{ portal_license_file  }}
    dest={{ portal_license_path | default("/opt/vnsportal/tomcat-instance1/") }}
    mode=0644
- name: Restart SD-WAN Portal instances
  import_tasks: restart_sdwan_portal.yml
