---
- name: Delete keys in known_hosts file
  lineinfile:
    path=/root/test
    regexp='^{{ vm_name }}'
    state=absent
  delegate_to: localhost
  become: "{{ 'no' if target_server_username == 'root' else 'yes' }}"
