dist: xenial
sudo: false
language: python
python:
    - "2.7"
    - "3.5"
install: 
  - sudo pip install ansible
  - sudo pip install pytest
  - sudo pip install mock

script:
  - export PYTHONPATH=$PWD:/usr/local/lib/python2.7/dist-packages:/usr/local/lib/python3.5/dist-packages
  - python -m pytest
  - yamllint roles
  - ansible-playbook -i inventory/local-tests.ini cluster.yml -vvv --syntax-check
  - ansible-playbook -i inventory/local-tests.ini upgrade-cluster.yml -vvv --syntax-check
  - ansible-playbook -i inventory/local-tests.ini addons.yml -vvv --syntax-check
  - ansible-playbook -i inventory/local-tests.ini reset-cluster.yml -vvv --syntax-check
os: linux
sudo: required
services:
  - docker
before_install:
  - pip install -U yamllint ansible