---

- hosts: masters
  become: true
  roles:
    - { role: cluster-default }
    - { role: cluster-path }
    - { role: cert, tags: cert }

- hosts: kube-cluster
  gather_facts: false
  become: true
  roles:
    - { role: cluster-default }
    - { role: cluster-path }
    - { role: container-runtime, tags: container-runtime }

- hosts: etcds
  become: true
  roles:
   - { role: cluster-default }
   - { role: cluster-path }
   - { role: etcd, tags: etcd }

- hosts: masters
  become: true
  roles:
    - { role: cluster-default }
    - { role: cluster-path }
    - { role: k8s-kubeconfig, node_role: 'master' }
    - { role: k8s-setup, node_role: 'master', tags: master-setup }
    - { role: k8s-addon, addon: "{{ addons.kubedns }}" }
    - { role: k8s-addon, addon: "{{ addons.kubeproxy }}" }

- hosts: nodes
  become: true
  roles:
    - { role: cluster-default }
    - { role: cluster-path }
    - { role: k8s-kubeconfig, node_role: 'node' }
    - { role: k8s-setup, node_role: 'node', tags: node-setup }

- hosts: masters
  become: true
  gather_facts: false
  roles:
    - { role: cluster-default }
    - { role: cluster-path }
    - { role: k8s-cni, when: cni_enable }
