---
## Nginx is installed as dependencies of hublin role
- hosts: hublin-master
  vars_files:
    - config.yml
  roles:
    - hosts
    - mongodb
    - redis
    - coturn
    - node
    - hublin

- hosts: hublin-slave
  vars_files:
    - config.yml
  roles:
    - node
    - coturn
    - hublin

- hosts: hublin-slave-local
  connection: local
  vars_files:
    - config.yml
  roles:
    - node
    - coturn
    - hublin
