# Use this to execute operations on host_groups. E.g.
#   ansible-playbook -i hosts stack_op.yml --extra-vars "op=restart host_group=stroom_services_stack"
---
- name: Get the operation to perform
  hosts: all
  vars_prompt:
   - name: op
     prompt: "What operation would you like to perform? Give the full script name plus arguments. E.g. remove.sh -y"
     private: no
   - name: stack_type
     prompt: "What host group would you like to perform this on? [stroom_services_stack|stroom_dbs_stack|stroom_and_proxy_stack]"
     private: no
  # We can prompt the user for a variable but it won't be  shared with other plays in the playbook.
  # To share it we can set it as a fact.
  tasks:

    - set_fact:
        op: "{{op}}"

    - set_fact:
        stack_type: "{{stack_type}}"

    - debug:
        var: stack_type
        verbosity: 2

- name: asda 
  vars_files:
    - ./variables.yml
    - ../global_variables.yml
    - ../config/user_settings.yml
  hosts: all
  roles:
    - roles/stack/op

