booterizer:
  installmirror:  "https://sgi-irix.s3.amazonaws.com"
  irixversion:    "6.5.30"
  installmethod:  "ftp"
  clientname:     "origin"
  clientdomain:   "dillera.org"
  network:        "192.168.251.0" 
  netmask:        "255.255.255.0"
  hostip:         "192.168.251.99"
  clientip:       "192.168.251.82"
  clientether:    "08:00:69:0d:a4:8e"
  bridgenic:      "en0"
  myuser:         "dillera"
  myshell: "/usr/nekoware/bin/bash"
