---
- name: Updated local config, ready to send to host
  hosts: localhost
  vars_files:
    - ./variables.yml
    - ../global_variables.yml
    - ../config/user_settings.yml
  roles:
    - roles/config/update
