---

- name: Check kubelet SSL certificate key files
  stat:
    path: "{{ kubelet }}"
  register: check_kubelet_ssl_file

- name: Generate kubelet SSL certificate json files
  when: not check_kubelet_ssl_file.stat.exists
  template:
    src: kubelet-csr.json.j2
    dest: "{{ pki_dir }}/kubelet-csr.json"
  register: gen_kubelet_json_file

- name: Create kubelet SSL certificate key files
  when: not check_kubelet_ssl_file.stat.exists
  shell: |
    {{ bin_dir }}/cfssl gencert \
      -ca={{ pki_dir }}/ca.pem \
      -ca-key={{ pki_dir }}/ca-key.pem \
      -config={{ ca_config }} \
      -hostname="{{ ansible_hostname }}" \
      -profile={{ cert_info_profile }} \
      {{ pki_dir }}/kubelet-csr.json | \
      {{ bin_dir }}/cfssljson -bare {{ pki_dir }}/kubelet
  register: create_kubelet_ssl_file
