---

- import_tasks: prepare.yaml
  tags: always

- import_tasks: nodes.yaml
  tags: nodes

- import_role:
    name: etcd
    tasks_from: backup.yaml
  delegate_to: "{{ groups.masters.0 }}"
  run_once: true
  tags: etcd

- import_tasks: project.yaml
  delegate_to: "{{ groups.masters.0 }}"
  run_once: true
  tags: project


