- name: Restore the /etc/hosts files on the VSDs
  copy:
    dest: "/etc/hosts"
    src: "{{ metro_backup_root }}/{{ inventory_hostname }}/hosts"
    mode: 0644
    owner: "{{ vsd_default_username }}"
    group: "{{ vsd_default_username }}"
  remote_user: "{{ vsd_default_username }}"
