- name: 创建addons目录
  file: name=/etc/kubernetes/addons state=directory

- name: 拷贝calico-rbac.yaml
  template: src=calico-rbac.yaml dest=/etc/kubernetes/addons

- name: 拷贝calico.yaml
  template: src=calico.yaml dest=/etc/kubernetes/addons

- name: 拉取kube-controllers镜像
  shell: "ansible all -m docker_image -a 'name=calico/kube-controllers tag={{ CALICO_VER }} source=pull timeout=3600'"

- name: 拉取cni镜像
  shell: "ansible all -m docker_image -a 'name=calico/cni tag={{ CALICO_VER }} source=pull timeout=3600'"
  
- name: 拉取pod2daemon-flexvol镜像
  shell: "ansible all -m docker_image -a 'name=calico/pod2daemon-flexvol tag={{ CALICO_VER }} source=pull timeout=3600'"

- name: 拉取node镜像
  shell: "ansible all -m docker_image -a 'name=calico/node tag={{ CALICO_VER }} source=pull timeout=3600'"
    
- name: 部署calico-rbac
  shell: "kubectl apply -f /etc/kubernetes/addons/calico-rbac.yaml"
  
- name: 部署calico
  shell: "kubectl apply -f /etc/kubernetes/addons/calico.yaml"
