---
- name: add GitHub deployment key
  authorized_key:
    user: deploy
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMJ6RY33/20jjRJtZcdFqkbFoHGAq6qsWgQhx8lfCwEQ deploy@webapps.flathub.org"
    key_options: 'command="/usr/bin/rrsync ~/flathub.org",no-agent-forwarding,no-port-forwarding,no-pty,no-user-rc,no-X11-forwarding'

- name: install nginx conf.d/flathub.conf
  template:
    src: nginx/flathub.conf.j2
    dest: /etc/nginx/conf.d/flathub.conf
    validate: /usr/local/sbin/ansible-validate-nginx-config %s conf.d/flathub.conf
  notify:
    - reload nginx
