---
- name: List the Virtual Machines on {{ target_server }}
  virt: command=list_vms
  register: virt_vms
  delegate_to: "{{ target_server }}"
  remote_user: "{{ target_server_username }}"
  become: "{{ 'no' if target_server_username == 'root' else 'yes' }}"

- import_tasks: dns_destroy_helper.yml
  when: inventory_hostname in virt_vms.list_vms

- name: Destroy the images directory
  file: path={{ images_path }}/{{ inventory_hostname }}
        state=absent
  delegate_to: "{{ target_server }}"
  remote_user: "{{ target_server_username }}"
  become: "{{ 'no' if target_server_username == 'root' else 'yes' }}"
