- include_role:
    name: check-skip-target-server
  vars:
    - target_server_list: ["kvm", "vcenter", "aws"]

- import_tasks: kvm.yml
  when: target_server_type is match("kvm")
  tags:
    - nsgv
    - nsgv-destroy

- import_tasks: vcenter.yml
  when: target_server_type is match("vcenter")
  tags:
    - nsgv
    - nsgv-destroy

- import_tasks: aws.yml
  when: target_server_type is match("aws")
  tags:
    - nsgv
    - nsgv-destroy
