- name: Get monit summary for stats processes
  vsd_monit:
    group: vsd-stats
  register: stats_proc
  remote_user: "{{ vsd_custom_username | default(vsd_default_username) }}"
  become: "{{ 'no' if vsd_custom_username | default(vsd_default_username) == 'root' else 'yes' }}"
  vars:
    ansible_become_pass: "{{ vsd_custom_password | default(vsd_default_password) }}"

- name: Print monit status when verbosity >= 1
  debug: var=stats_proc verbosity=1

- name: Write stats monit status to json file
  nuage_append: filename="{{ report_path }}" text="{{ inventory_hostname }} {{ stats_proc.state | to_nice_json }}\n"
  delegate_to: localhost
