---
- name: Web Browsers - Install snapd apt dependency
  become: true
  apt:
    name: "snapd"
    state: present

- name: Web Browsers - remove firefox* apt packages
  become: true
  apt:
    name: "firefox*"
    state: absent
    purge: "yes"
    autoremove: "yes"
  when: "'firefox' in snaps_web_browsers"

- name: Web Browsers - Install Confined Snaps - Chromium and Firefox
  become: true
  snap:
    name: "{{ item.name }}"
    channel: "{{ item.channel | default('stable')}}"
    classic: "{{ item.classic | default('no')}}"
  with_items: "{{ snaps_web_browsers }}"

# https://github.com/ansible/ansible/issues/58403
- name: Web Browsers - Setup Snap Plugs
  become: "yes"
  become_method: sudo
  changed_when: false
  shell: 'snap connect {{ item.app }}:{{ item.plug }}'
  with_items: "{{ snaps_web_browsers_plugs }}"
