---
zookeeper_version: 3.4.6
zookeeper_url: http://www.us.apache.org/dist/zookeeper/zookeeper-{{zookeeper_version}}/zookeeper-{{zookeeper_version}}.tar.gz

apt_cache_timeout: 3600

client_port: 2181
follower_port: 2888
leader_port: 3888

init_limit: 5
sync_limit: 2
tick_time: 2000
zoo_id: 1
data_dir: /var/lib/zookeeper
log_dir: /var/log/zookeeper
zookeeper_dir: /opt/zookeeper-{{zookeeper_version}}

refresh_zookeeper: no
zookeeper_data_dir: /data/zookeeper