---
- name: Drop the Kafka durable data
  file:
    path: "{{ kafka_data_dir }}"
    state: absent
  when: "{{ refresh_kafka }}"

- name: Create the durable Kafka data directory
  file:
    path: "{{ kafka_data_dir }}"
    state: directory
    mode: 0755
    recurse: yes

- name: Kill the Kafka container
  docker:
    name: kafka
    image: michaeldrogalis/docker-kafka:0.3.6
    state: killed
  when: "{{ refresh_kafka }}"

- name: Kill the Kafka data container
  docker:
    name: kafka_data
    image: alpine:3.2
    state: killed
  when: "{{ refresh_kafka }}"

- name: Create the Kafka data container
  docker:
    name: kafka_data
    image: alpine:3.2
    detach: yes
    state: restarted
    restart_policy: always
    restart_policy_retry: 128
    command: echo 'Kafka data container'
    volumes:
      - "{{ kafka_data_dir }}:/tmp/kafka"

- name: Run Kafka container
  docker:
    name: kafka
    image: michaeldrogalis/docker-kafka:0.3.6
    net: host
    detach: yes
    state: restarted
    publish_all_ports: yes
    restart_policy: always
    restart_policy_retry: 128
    volumes_from:
      - kafka_data
    env:
      KAFKA_BROKER_ID: "{{ groups.kafka | natural_index_of(inventory_hostname) }}"
      KAFKA_ADVERTISED_HOST_NAME: "{{ inventory_hostname }}"
      KAFKA_ZOOKEEPER_CONNECT: "{{ groups.zookeeper | join(',') }}"

- name: Wait for Kafka to come up
  wait_for: port=9092 delay=15 timeout=60
