---

# system paths
bin_dir: /usr/local/bin
sbin_dir: /usr/local/sbin
cache_dir: /tmp
ld_config_dir: /etc/ld.so.conf.d

systemd_service_dir: /lib/systemd/system
systemd_env_dir: /etc/default
systemd_dropin_dir: /etc/systemd/system

# kubernetes paths
etc_dir: /etc/kubernetes
manifest_dir: /etc/kubernetes/manifests
addon_dir: /etc/kubernetes/addons
kubelet_config_dir: /var/lib/kubelet
cni_etc_dir: /etc/cni/net.d
cni_bin_dir: /opt/cni/bin
audit_policy_dir: /etc/kubernetes/audit
audit_log_dir: /var/log/kubernetes
encryption_config_dir: /etc/kubernetes/encryption
haproxy_config_dir: /etc/haproxy

admin_kubeconfig: "{{ etc_dir }}/admin.conf"
scheduler_kubeconfig: "{{ etc_dir }}/scheduler.conf"
controller_manager_kubeconfig: "{{ etc_dir }}/controller-manager.conf"
kubelet_kubeconfig: "{{ etc_dir }}/kubelet.conf"
bootstrap_kubeconfig: "{{ etc_dir }}/kubelet-bootstrap.conf"
kubelet_config: "{{ kubelet_config_dir }}/config.yml"
audit_log: "{{ audit_log_dir }}/audit.log"
audit_policy: "{{ audit_policy_dir }}/policy.yml"
encryption_config: "{{ encryption_config_dir }}/config.yml"
haproxy_config: "{{ haproxy_config_dir }}/haproxy.cfg"

# etcd paths
etcd_data_dir: /var/lib/etcd
etcd_wal_dir: /var/lib/etcd/wal
etcd_config_dir: /etc/etcd
etcd_config_file: /etc/etcd/config.yml

# container runtime paths
docker_data_dir: /var/lib/docker
docker_config_dir: /etc/docker
docker_shim_dir: /var/lib/dockershim

containerd_data_dir: /var/lib/containerd
containerd_config_dir: /etc/containerd

nvidia_runtime_config_dir: /etc/nvidia-container-runtime
libnvidia_header_file: /usr/local/include/nvc.h
libnvidia_lib_dir: /usr/local/lib/libnvidia

# cert paths
ca_config: "{{ cache_dir }}/ca-config.json"
pki_dir: /etc/kubernetes/pki
etcd_pki_dir: "{{ pki_dir }}/etcd"

ca: "{{ pki_dir }}/ca.pem"
ca_key: "{{ pki_dir }}/ca-key.pem"
etcd_ca: "{{ etcd_pki_dir }}/etcd-ca.pem"
etcd_ca_key: "{{ etcd_pki_dir }}/etcd-ca-key.pem"
etcd_cert: "{{ etcd_pki_dir }}/etcd.pem"
etcd_cert_key: "{{ etcd_pki_dir }}/etcd-key.pem"
kubelet: "{{ pki_dir }}/kubelet.pem"
kubelet_key: "{{ pki_dir }}/kubelet-key.pem"
admin: "{{ pki_dir }}/admin.pem"
admin_key: "{{ pki_dir }}/admin-key.pem"
apiserver: "{{ pki_dir }}/apiserver.pem"
apiserver_key: "{{ pki_dir }}/apiserver-key.pem"
scheduler: "{{ pki_dir }}/scheduler.pem"
scheduler_key: "{{ pki_dir }}/scheduler-key.pem"
controller_manager: "{{ pki_dir }}/controller-manager.pem"
controller_manager_key: "{{ pki_dir }}/controller-manager-key.pem"
front_ca: "{{ pki_dir }}/front-proxy-ca.pem"
front_ca_key: "{{ pki_dir }}/front-proxy-ca-key.pem"
front_client: "{{ pki_dir }}/front-proxy-client.pem"
front_client_key: "{{ pki_dir }}/front-proxy-client-key.pem"
sa_public_key: "{{ pki_dir }}/sa.pub"
sa_private_key: "{{ pki_dir }}/sa.key"