---
- name: Initialization Checkpoint Start
  hosts: localhost
  gather_facts: false
  roles:
  - installer_checkpoint

- name: Prune Checkpoint Start
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Set Prune 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_prune:
          title:  "OpenShift Prune"
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- name: OpenShift Prune
  hosts: masters[0]
  roles:
  - role: openshift_prune

- name: Prune Checkpoint End
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Set Prune 'Complete'
    run_once: true
    set_stats:
      data:
        installer_phase_prune:
          title:  "OpenShift Prune"
          status: "Complete"
          end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
