---
gnome_keybindings:
  # Window and Application switching
  - key: "/org/gnome/desktop/wm/keybindings/switch-applications"
    value: "['<Super>Tab']"
  - key: "/org/gnome/desktop/wm/keybindings/switch-applications-backward"
    value: "['<Shift><Super>Tab']"
  - key: "/org/gnome/desktop/wm/keybindings/switch-windows"
    value: "['<Alt>Tab']"
  - key: "/org/gnome/desktop/wm/keybindings/switch-windows-backward"
    value: "['<Shift><Alt>Tab']"
  # Move windows (<Ctrl><Alt>Direction interferes and wasn't reliable)
  - key: "/org/gnome/desktop/wm/keybindings/move-to-monitor-down"
    value: "['<Shift><Alt>Down']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-monitor-up"
    value: "['<Shift><Alt>Up']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-monitor-left"
    value: "['<Shift><Alt>Left']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-monitor-right"
    value: "['<Shift><Alt>Right']"
    # Move workspaces
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-down"
    value: "['<Shift><Super>Down']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-up"
    value: "['<Shift><Super>Up']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-left"
    value: "['<Shift><Super>Left']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-right"
    value: "['<Shift><Super>Right']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-last"
    value: "['<Shift><Super>End']"
    # Close Windows (added '<Super>w')
  - key: "/org/gnome/desktop/wm/keybindings/close"
    value: "['<Super>w','<Alt>F4']"
    # Launch Terminal (added '<Super>t')
  - key: "/org/gnome/settings-daemon/plugins/media-keys/terminal"
    value: "['<Ctrl><Alt>t']"
    # Lock Screen
  - key: "/org/gnome/settings-daemon/plugins/media-keys/screensaver"
    value: "['<Super>l']"
