---
# https://github.com/iancleary/ansible-role-zsh_antibody
antibody_bundles:
  # Bundles from the default repo (robbyrussell's oh-my-zsh) only need a name
  # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins
  #
  # `name` is required (any valid file name will do so long as it's unique for the bundles)
  # `url` is git username/repo
  # `version` is git release and is required if `url` is define
  # - name: ansible
  # - name: aws
  # - name: docker
  # - name: docker-compose
  - name: gitfast
  # - name: pipenv
  - name: poetry
  - name: yarn
  - name: zsh
  # Syntax highlighting bundle.
  - name: zsh-syntax-highlighting
    git:
      user: zsh-users
      repo: zsh-syntax-highlighting
      version: 0.7.1
  # # Autosuggestions
  # - name: zsh-autosuggestions # `name` is required (any valid file name will do so long as it's unique for the bundles)
  #   repo:
  #     user: zsh-users
  #     repo: zsh-autosuggestions
  #     version: v0.6.4
  - name: powerlevel10k
    skip_zshrc_plugin:
    git:
      user: romkatv
      repo: powerlevel10k
      version: v1.12.0
