---
- name: Initialization Checkpoint Start
  hosts: localhost
  gather_facts: false
  roles:
  - installer_checkpoint

- name: Expand PV Checkpoint Start
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Set Expand PV 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_expand_pv:
          title:  "OpenShift Expand PV"
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- hosts: all
  roles:
  - role: openshift_expand_pv

- name: Expand PV Checkpoint End
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Set Expand PV 'Complete'
    run_once: true
    set_stats:
      data:
        installer_phase_expand_pv:
          title:  "OpenShift Expand PV"
          status: "Complete"
          end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
