---
- include: Debian.yml
  when: ansible_os_family == "Debian"
  tags: hublin

- include: RedHat.yml
  when: ansible_os_family == "RedHat"
  tags: hublin

- name: Clone hublin repository
  git: >
    repo=https://ci.open-paas.org/stash/scm/meet/meetings.git
    dest=/srv/hublin
  tags: hublin

- name: Install hublin backend dependencies (npm)
  command: >
    npm install
    chdir=/srv/hublin
    creates=/srv/hublin/npm-debug.log
  tags: hublin

- name: Install hublin frontend dependencies (bower)
  command: >
    bower install --allow-root
    chdir=/srv/hublin
    creates=/srv/hublin/frontend/components
  tags: hublin

- name: Deploy hublin init script
  copy: >
    src=hublin-init
    dest=/etc/init.d/hublin
    mode=0750
  notify:
    - Restart hublin service
  tags: hublin

- name: Deploy database configuration
  template: >
    src=db.json
    dest=/srv/hublin/config/db.json
    mode=0644
  notify:
    - Restart hublin service
  tags: hublin

- name: Deploy main configuration
  template: >
    src=default.production.json
    dest=/srv/hublin/config/default.production.json
    mode=0644
  notify:
    - Restart hublin service
  tags: hublin
