---

- name: Enable Admission Webhook on Master
  yedit:
    src: '{{ openshift_admission_webhook_master_config }}'
    key: admissionConfig.pluginConfig.{{ item }}.configuration
    value: |
      apiVersion: v1
      disable: false
      kind: DefaultAdmissionConfig
    state: present
    backup: yes
  with_items:
   - Initializers
   - ValidatingAdmissionWebhook
   - MutatingAdmissionWebhook

- import_role:
    name: common
    tasks_from: restart-master.yaml
