---
- name: Initialization Checkpoint Start
  hosts: localhost
  gather_facts: false
  roles:
  - installer_checkpoint

- name: Quota Install Checkpoint Start
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Set Quota install 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_quota:
          title:  "OpenShift Quota"
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- name: OpenShift Quota
  hosts: masters[0]
  roles:
  - role: openshift_quota

- name: Quota Install Checkpoint End
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Set Quota install 'Complete'
    run_once: true
    set_stats:
      data:
        installer_phase_quota:
          title:  "OpenShift Quota"
          status: "Complete"
          end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
