- block:

  - name: Measure RTT between current and other VSD
    shell: nping --tcp -p 3306 -c 10 {{ other_node }} | grep 'Max rtt:*' | cut -dm -f1 | sed 's/Max rtt://1'
    register: measured_rtt

  - name: Print measured RTT
    debug: var=measured_rtt

  - name: Check if RTT lower than required
    assert:
      that: "(measured_rtt.stdout | int) <= vsd_max_rtt"
      msg: >-
        RTT between {{ other_node }} and {{ current_node }} is {{ measured_rtt.stdout | int }} milliseconds.
        Quitting. Current maximum RTT for proper cluster performance is set to {{ vsd_max_rtt }} milliseconds.
        RTT test parameters may be modified in your common.yml file.
    ignore_errors: "{{ vsd_ignore_errors_rtt_test | default(false) }}"

  - name: Store the RTT result object between current and other VSD
    set_fact:
      single_result: {
        src: '{{ current_node }}',
        dst: '{{ other_node }}',
        rtt: '{{ measured_rtt.stdout }}'
      }

  when: delegate_node is not defined

- block:

  - name: Measure RTT between delegated and other VSD
    shell: nping --tcp -p 3306 -c 10 {{ other_node }} | grep 'Max rtt:*' | cut -dm -f1 | sed 's/Max rtt://1'
    register: measured_delegate_rtt
    delegate_to: "{{ delegate_node | default ('NONE') }}"

  - name: Print measured RTT
    debug: var=measured_delegate_rtt

  - name: Check if RTT lower than required
    assert:
      that: "(measured_delegate_rtt.stdout | int) <= vsd_max_rtt"
      msg: >-
        RTT between {{ other_node }} and {{ current_node }} is {{ measured_delegate_rtt.stdout | int }} milliseconds.
        Quitting. Current maximum RTT for proper cluster performance is set to {{ vsd_max_rtt }} milliseconds.
        RTT test parameters may be modified in your common.yml file.
    ignore_errors: "{{ vsd_ignore_errors_rtt_test | default(false) }}"

  - name: Store the RTT result object between delegated and other VSD
    set_fact:
      single_result: {
        src: '{{ delegate_node }}',
        dst: '{{ other_node }}',
        rtt: '{{ measured_delegate_rtt.stdout }}'
      }

  when: delegate_node is defined

- name: Add the result to previouly calculated RTT results
  set_fact:
    vsd_rtt_test_results: '{{ vsd_rtt_test_results + [single_result] }}'
