---

- name: "Check {{ pkg.name }} binary already exists"
  stat: path="{{ cache_dir }}/{{ pkg.file }}-{{ base[''+ pkg.name].version }}"
  register: pkg_check

- name: "Downloading {{ pkg.name }} file"
  when: not pkg_check.stat.exists
  get_url:
    url: "{{ pkg.url }}/{{ pkg.file }}"
    dest: "{{ cache_dir }}/{{ pkg.file }}-{{ base[''+ pkg.name].version }}"
    validate_certs: False
  environment: "{{ proxy_env }}"
  register: pkg_download

- name: "Copy {{ pkg.name }} file to release directory"
  copy:
    src: "{{ cache_dir }}/{{ pkg.file }}-{{ base[''+ pkg.name].version }}"
    dest: "{{ pkg.dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0755
    remote_src: True
  with_items: "{{ pkg['symlinks'] }}"
  register: pkg_copy
