upgrade_complete_flag_command: "yes 'yes' | VSD_VERSION={{ vsd_version.stdout }} VSD_BUILD={{ vsd_build.stdout }} /opt/vsd/bin/vsd-upgrade-complete"
turn_on_api_command: "yes 'yes' | VSD_VERSION={{ vsd_version.stdout }} VSD_BUILD={{ vsd_build.stdout }} /opt/vsd/bin/turn-on-api"
change_credentials_command: "/opt/vsd/install/change_credential.sh -j '{{ vsd_user_cred }}'"
