---
- name: restart buildbot-master
  service:
    name: buildbot-master
    state: restarted

- name: reconfig buildbot-master
  service:
    name: buildbot-master
    state: reloaded

- name: restart buildbot-master required
  debug:
    msg: "Restarting buildbot-master service is required to pick up new config"
