---

dependencies:
  - { role: common/os-check }
  - { role: download/package, when: container_runtime == 'docker' or container_runtime == 'nvidia-docker', pkg: "{{ package.docker }}" }
  - { role: download/package, when: container_runtime == 'nvidia-docker', pkg: "{{ package.nvidia_docker }}" }
  - { role: download/package, when: container_runtime == 'nvidia-docker', pkg: "{{ package.nvidia_container_runtime }}" }
  - { role: download/package, when: container_runtime == 'nvidia-docker', pkg: "{{ package.libnvidia_container }}" }
  - { role: download/package, when: container_runtime == 'containerd', pkg: "{{ package.containerd }}" }