- block:
  - name: Display if skipping predeploy
    debug:
      msg:
        - "****************************************************"
        - "Skipping as action is in skip actions list"
        - "****************************************************"

  - name: Stop playbook
    meta: end_play

  when:
    - skip_actions is defined
    - action in skip_actions
