---
- name: Initialization Checkpoint Start
  hosts: localhost
  gather_facts: false
  roles:
  - installer_checkpoint

- name: Docker GC Checkpoint Start
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Set Docker GC 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_docker_gc:
          title:  "Docker GC"
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- name: Docker GC
  hosts: all
  roles:
  - role: docker_gc

- name: Docker GC Checkpoint End
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Set Docker GC 'Complete'
    run_once: true
    set_stats:
      data:
        installer_phase_docker_gc:
          title:  "OpenShift Docker GC"
          status: "Complete"
          end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
