---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - stack_volumes_dir is defined

  # TODO this ensures all cert/key files are absent even if the service 
  # is not in the stack. Could make it aware of which services are present
- name: "Deleting development certs/keys"
  include_tasks: delete_certs.yml
  loop: "{{ service_dev_certs }}"
  loop_control:
    loop_var: _service_dev_certs
    label: "{{ _service_dev_certs.path }}"
