---
- name: NordVPN - Install deb from their website
  become: true
  apt:
    deb: >-
      https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn-release_1.0.0_all.deb

- name: NordVPN - Install apt package
  become: true
  apt:
    name: 'nordvpn'
    state: latest
    update_cache: "yes"
