- import_tasks: prepare.yaml
  tags: always

- import_tasks: aws_s3.yaml
  tags: aws_s3
  when: aws_s3 is defined and aws_s3 | bool

# Cannot stop the node
# Need kubelet daemon running at least for 3.10 and 3.11
# - import_role:
#    name: common
#    tasks_from: stop-node.yaml
#  tags: nodes

- import_role:
    name: common
    tasks_from: stop-all.yaml
  tags: masters, etcd

- import_tasks: restore-node.yaml
  tags:
    - nodes
    - masters

- import_role:
    name: etcd
    tasks_from: restore.yaml
  when: "'masters' in group_names"
  tags: etcd