- name: Ensure backup_prefix is defined
  fail:
    msg: Ensure backup_prefix is not defined or empty
  when: backup_prefix is not defined and backup_prefix == ''
  run_once: true

- name: Ensure directories restore exist
  file:
    path: '{{ restore_root }}/{{ backup_prefix }}/{{ item }}'
    state: directory
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'
  delegate_to: localhost
  run_once: true
  with_items:
    - '{{ groups["nodes"] }}'
