---
- name: Converge
  hosts: all
  become: true

  vars:
    php_opcache_enable: false

  environment:
    TERM: xterm

  pre_tasks:
    - name: System Information
      debug:
        msg: "Installing on ansible_os_family {{ ansible_os_family }} ansible_distribution_major_version {{ ansible_distribution_major_version }}"

  post_tasks:
    - name: Test Devmaster
      become: true
      become_user: "{{ aegir_user_name }}"
      become_method: "{{ ansible_become_method_aegir }}"
      command: "{{ devmaster_test_command }}"

  roles:
    - role: geerlingguy.mysql
    - role: opendevshop.devmaster
