- block:

  - name: Get vsd node(s) information
    import_role:
      name: common
      tasks_from: vsd-node-info.yml
    vars:
      vsd_hostname: "{{ vsd_fqdn }}"
    run_once: true

  - name: Enable stats
    include_role:
      name: common
      tasks_from: vstat-enable-stats.yml
    vars:
      clear_stats: true
    loop: "{{ groups['primary_vsds'] }}"
    loop_control:
      loop_var: vsd
    run_once: true

  - name: Change backup ES to become Primary
    include_role:
      name: common
      tasks_from: vstat-nfs-configuration.yml
    vars:
      clear_old_config: true
