---
- name: Initialization Checkpoint Start
  hosts: localhost
  gather_facts: false
  roles:
  - installer_checkpoint

- name: Local Volume Checkpoint Start
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Set Local Volume 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_expand_pv:
          title:  "OpenShift Local Volume"
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- hosts: all
  roles:
  - role: openshift_local_volume

- name: Local Volume Checkpoint End
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Set Local Volume 'Complete'
    run_once: true
    set_stats:
      data:
        installer_phase_expand_pv:
          title:  "OpenShift Local Volume"
          status: "Complete"
          end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
