- name: Ensure .docker exist
  file:
    path: "{{ item }}/.docker"
    state: directory
    mode: 0644
    owner: root
    group: root
  with_items:
  - /root
  - /var/lib/origin

- name: Apply config.json template
  template:
    src: config.json.j2
    dest: "{{ item }}/.docker/config.json"
  with_items:
  - /root
  - /var/lib/origin

- name: Restart OpenShift Node
  import_role:
    name: common
    tasks_from: restart-node.yaml

  
