---
# The deadsnakes PPA is required to install python3.5 on Trusty.
# Xenial comes with python3.5 installed.
- name: add deadsnakes repository
  apt_repository:
    repo: "ppa:deadsnakes/ppa"
  when: ansible_distribution_release == 'bionic'
  tags:
    - install
    - install:system-requirements

- name: install python3.5, 3.6 and 3.8
  apt:
    name: "{{ item }}"
  with_items:
    - python3.5
    - python3.5-dev
    - python3.6
    - python3.6-dev
    - python3.8
    - python3.8-dev
  when: ansible_distribution_release == 'bionic'
  tags:
    - install
    - install:system-requirements
