---
- name: Converge
  hosts: all
  become: true

  vars:
    supervisor_unix_http_server_enable: false
    supervisor_inet_http_server_enable: true
    supervisor_inet_http_server_port: '*:9001'

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Install required dependencies.
      yum: name=initscripts state=present
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_version.split('.')[0] == '6'

  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.supervisor

  tasks:
    - name: Validate Supervisor is responding to requests through the web UI.
      uri:
        url: http://localhost:9001/
        method: GET
        user: "{{ supervisor_user }}"
        password: "{{ supervisor_password }}"
        status_code: 200

    - name: Validate Supervisor rejects unauthenticated requests to the web UI.
      uri:
        url: http://localhost:9001/
        method: GET
        user: "{{ supervisor_user }}"
        password: "fizzbuzz"
        status_code: 401
