kind: List
metadata: {}
apiVersion: v1
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    annotations:
      openshift.io/quota-tier: Medium
    labels:
      quota-tier: Medium
    name: quota
  spec:
    hard:
      cpu: "4"
      memory: 8Gi
    scopes:
    - NotTerminating
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    annotations:
      openshift.io/quota-tier: Medium
    labels:
      quota-tier: Medium
    name: burst-quota
  spec:
    hard:
      cpu: "6"
      memory: 12Gi
- apiVersion: v1
  kind: LimitRange
  metadata:
    annotations:
      openshift.io/quota-tier: Medium
    labels:
      quota-tier: Medium
    name: limits
  spec:
    limits:
    - max:
        cpu: "2"
        memory: 4Gi
      min:
        cpu: 20m
        memory: 128Mi
      type: Pod
    - default:
        cpu: "1"
        memory: 1Gi
      defaultRequest:
        cpu: 50m
        memory: 256Mi
      max:
        cpu: "2"
        memory: 4Gi
      min:
        cpu: 20m
        memory: 256Mi
      type: Container
