kind: List
metadata: {}
apiVersion: v1
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    annotations:
      openshift.io/quota-tier: Large
    labels:
      quota-tier: Large
    name: quota
  spec:
    hard:
      cpu: "12"
      memory: 32Gi
    scopes:
    - NotTerminating
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    annotations:
      openshift.io/quota-tier: X-Large
    labels:
      quota-tier: X-Large
    name: burst-quota
  spec:
    hard:
      cpu: "16"
      memory: 64Gi
- apiVersion: v1
  kind: LimitRange
  metadata:
    annotations:
      openshift.io/quota-tier: X-Large
    labels:
      quota-tier: X-Large
    name: limits
  spec:
    limits:
    - max:
        cpu: "6"
        memory: 16Gi
      min:
        cpu: 20m
        memory: 256Mi
      type: Pod
    - default:
        cpu: "4"
        memory: 8Gi
      defaultRequest:
        cpu: 100m
        memory: 512Mi
      max:
        cpu: "6"
        memory: 16Gi
      min:
        cpu: 20m
        memory: 256Mi
      type: Container
