kind: List
metadata: {}
apiVersion: v1
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    annotations:
      openshift.io/quota-tier: X-Small
    labels:
      quota-tier: X-Small
    name: quota
  spec:
    hard:
      cpu: "1"
      memory: 2Gi
    scopes:
    - NotTerminating
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    annotations:
      openshift.io/quota-tier: X-Small
    labels:
      quota-tier: X-Small
    name: burst-quota
  spec:
    hard:
      cpu: "2"
      memory: 4Gi
- apiVersion: v1
  kind: LimitRange
  metadata:
    annotations:
      openshift.io/quota-tier: X-Small
    labels:
      quota-tier: X-Small
    name: limits
  spec:
    limits:
    - max:
        cpu: "1"
        memory: 1Gi
      min:
        cpu: 10m
        memory: 128Mi
      type: Pod
    - default:
        cpu: 250m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 256Mi
      max:
        cpu: "1"
        memory: 1Gi
      min:
        cpu: 10m
        memory: 128Mi
      type: Container
