- name: Get monit summary for vsd processes
  vsd_monit:
    group: all
  register: vsd_proc
  remote_user: "{{ vsd_custom_username | default(vsd_default_username) }}"

- name: Print monit status when verbosity >= 1
  debug: var=vsd_proc verbosity=1

- name: Write vsd monit status separator to log file
  nuage_append: filename="{{ report_path }}" text="-----VSD Monit Status-----\n"
  delegate_to: localhost

- name: Write vsd monit status to log file
  nuage_append: filename="{{ report_path }}" text="{{ inventory_hostname }} {{ vsd_proc.state | to_nice_json }}\n"
  delegate_to: localhost
