---
- name: Nodejs - Ensure dependencies are present.
  become: true
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Nodejs - Add Nodesource apt key.
  become: true
  apt_key:
    url: >
      https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Nodejs - Add NodeSource repositories for Node.js.
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - >-
      deb https://deb.nodesource.com/node_{{ nodejs_version }}
       {{ ansible_distribution_release }} main
    - >-
      deb-src https://deb.nodesource.com/node_{{ nodejs_version }}
       {{ ansible_distribution_release }} main
  register: node_repo

- name: Nodejs - Update apt cache if repo was added.
  become: true
  apt: update_cache=yes
  when: node_repo.changed
  tags: ['skip_ansible_lint']

- name: Nodejs - Ensure Node.js is installed.
  become: true
  apt:
    name: "nodejs={{ nodejs_version|regex_replace('x', '') }}*"
    state: present
