---
node_exporter_version: 0.18.1
node_exporter_textfile_dir: /var/lib/node_exporter
node_exporter_enabled_collectors:
  - systemd
  - textfile:
      directory: "{{ node_exporter_textfile_dir }}"
node_exporter_disabled_collectors: []
