---

- hosts: add-nodes
  gather_facts: false
  become: true
  roles:
    - { role: cluster-default }
    - { role: cluster-path }
    - { role: container-runtime, tags: container-runtime }

- hosts: add-nodes
  become: true
  roles:
    - { role: cluster-default }
    - { role: cluster-path }
    - { role: k8s-kubeconfig, node_role: 'node' }
    - { role: k8s-setup, node_role: 'node', tags: node-setup }