apply_log: "innobackupex --apply-log --use-memory=4G {{ db_backup_status.path }}"
purge_cmd:
  - "mysql -e 'TRUNCATE TABLE AuditRecordData' ejbca"
  - "mysql -e 'TRUNCATE TABLE ALARM' vsddb"
  - "mysql -e 'TRUNCATE TABLE EVENT_LOG' vsddb"
purge_cmd_with_custom_pass:
  - "mysql -p{{ vsd_mysql_password}} -e 'TRUNCATE TABLE AuditRecordData' ejbca"
  - "mysql -p{{ vsd_mysql_password}} -e 'TRUNCATE TABLE ALARM' vsddb"
  - "mysql -p{{ vsd_mysql_password}} -e 'TRUNCATE TABLE EVENT_LOG' vsddb"
vsd_backup_dir: "/tmp/vsd_backup_dir/"
backup_cmd: "/media/CDROM/vsd-backup.sh -a -m -c -b {{ vsd_backup_dir }}"
gw_purge_time: 86400
