---

- name: See if {{ remote_db_dump_files_dir }}/{{ item.filename }} exists
  stat:
    path: "{{ remote_db_dump_files_dir }}/{{ item.filename }}"
  register: _dump_file_info

- name: Ensure {{ item.filename }} exists
  assert:
    that:
      - _dump_file_info.stat.exists == true

- name: Ensure we have gunzip
  become: true
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gzip

- name: Wait for the DB to be up
  shell: >-
    docker exec -i stroom-all-dbs sh -c
    'mysqladmin status -h"127.0.0.1" -u"{{ item.username }}" -p"{{ item.password }}"'
  register: _cmd_result
  until: _cmd_result.rc == 0
  retries: 20
  delay: 1

- name: Run the DB import for {{ remote_db_dump_files_dir }}/{{ item.filename }}
  shell: >-
    gunzip < {{ remote_db_dump_files_dir }}/{{ item.filename }}
    | docker exec -i stroom-all-dbs sh -c
    'mysql --init-command="SET SESSION FOREIGN_KEY_CHECKS=0;" -h"127.0.0.1" -u"{{ item.username }}" -p"{{ item.password }}" {{ item.db_name }}'
