- block:

  - name: Change XMPP connection to TLS on VSD
    command: /opt/vsd/bin/ejmode allow -y
    delegate_to: "{{ vsd }}"
    when: xmpp_tls

  - name: wait for ejabberd-status and ejbca-status to become running
    monit_waitfor_service:
      name: "{{ ['ejabberd-status', 'ejbca-status'] }}"
      timeout_seconds: 600
      test_interval_seconds: 30
    delegate_to: "{{ vsd }}"

  remote_user: "{{ hostvars[vsd].vsd_custom_username | default(vsd_custom_username | default(vsd_default_username)) }}"
  become: "{{ 'no' if hostvars[vsd].vsd_custom_username | default(vsd_custom_username | default(vsd_default_username)) == 'root' else 'yes' }}"
  vars:
    ansible_become_pass: "{{ hostvars[vsd].vsd_custom_password | default(vsd_custom_password | default(vsd_default_password)) }}"
