---
- name: Check VSD License
  check_vsd_license_validity:
    vsd_auth:
      "{{ vsd_auth }}"
    required_days_left: "{{ vsd_license_required_days_left | default(-1) }}"
    vsd_version: "{{ vsd_version.stdout }}"
  register: license_valid
  delegate_to: localhost
  no_log: "{{ lookup('env', 'METROAE_NO_LOG') or 'true' }}"

- debug: var=license_valid verbosity=1
