---
- name: Check if ip address is in the network range
  assert:
    that: "{{ (ip_address | ipaddr( netaddr ~ '/' ~ netmask)) != None }}"
    msg: "IP Address {{ ip_address }} is not in network range defined by network address {{ netaddr }} and mask {{ netmask }}"
