- name: "Cleanup old backups"
  block:

  - name: Find all backup directories
    find:
      path: "{{ metro_backup_root }}"
      patterns: "backup-*-{{ hostvars['localhost'].backup_type | default(backup_component_name) }}"
      file_type: directory
    register: backup_dirs_find

  - name: Create empty list of backup files
    set_fact:
      backup_dirs_list: []

  - name: Append list of backup files
    set_fact:
      backup_dirs_list: "{{ backup_dirs_list + [item.path] }}"
    loop: "{{ backup_dirs_find.files }}"

  - name: Sort backup list
    set_fact:
      backup_dirs_list: "{{ backup_dirs_list | sort(reverse=true) }}"

  - name: Delete old backup files
    file:
      path: "{{ backup_dirs_list[item] }}/"
      state: absent
    loop: "{{ range([max_num_stored_backups, 1] | max, backup_dirs_list | length) | list }}"

  delegate_to: localhost
  when: max_num_stored_backups >= 0
