---
- name: Disable cloud-init systemd services
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - cloud-init
    - cloud-init-local
    - cloud-config
    - cloud-final
