
- include_role:
    name: common
    tasks_from: copy-qcow2
  when: not skip_copy_images | default(False)

- block:

  - name: Check to make sure there is an existing qcow image
    stat:
      path: "{{ images_path }}/{{ vm_name }}/{{ dest_filename | default(image_file_name) }}"
    register: statResult

  - name: check the result of image find command
    assert:
      that: statResult.stat.exists
      msg: >-
        Skipped copying qcow2 image and could not find the image
        at the given location - {{ images_path }}/{{ vm_name }}/{{ dest_filename | default(image_file_name) }}

  when: skip_copy_images | default(False)
