- name: Remove R from upgrade_from_version
  set_fact:
    upgrade_from: '{{ upgrade_from_version|upper|replace("R","") }}'

- name: Remove R from upgrade_to_version
  set_fact:
    upgrade_to: '{{ upgrade_to_version|upper|replace("R","") }}'

- name: Skip vstat upgrade for versions that do not require upgrade
  set_fact:
    upgrade_from_521: "{{ (upgrade_from|upper).split('U')[0] is version_compare('5.2.1', operator='eq', strict=True)
                          and ( (upgrade_to|upper).split('U')[0] is version_compare('5.2.2', operator='eq', strict=True)
                          or (upgrade_to|upper).split('U')[0] is version_compare('5.2.3', operator='eq', strict=True)
                          or (upgrade_to|upper).split('U')[0] is version_compare('5.3.1', operator='eq', strict=True)
                          or (upgrade_to|upper).split('U')[0] is version_compare('5.3.2', operator='eq', strict=True)
                          or (upgrade_to|upper).split('U')[0] is version_compare('5.3.3', operator='eq', strict=True)
                          or (upgrade_to|upper).split('U')[0] is version_compare('5.4.1', operator='eq', strict=True) ) }}"
    upgrade_from_522: "{{ (upgrade_from|upper).split('U')[0] is version_compare('5.2.2', operator='eq', strict=True)
                          and ( (upgrade_to|upper).split('U')[0] is version_compare('5.2.3', operator='eq', strict=True)
                          or (upgrade_to|upper).split('U')[0] is version_compare('5.3.1', operator='eq', strict=True)
                          or (upgrade_to|upper).split('U')[0] is version_compare('5.3.2', operator='eq', strict=True)
                          or (upgrade_to|upper).split('U')[0] is version_compare('5.3.3', operator='eq', strict=True)
                          or (upgrade_to|upper).split('U')[0] is version_compare('5.4.1', operator='eq', strict=True) ) }}"
    upgrade_from_523: "{{ (upgrade_from|upper).split('U')[0] is version_compare('5.2.3', operator='eq', strict=True)
                          and ( (upgrade_to|upper).split('U')[0] is version_compare('5.3.1', operator='eq', strict=True)
                          or (upgrade_to|upper).split('U')[0] is version_compare('5.3.2', operator='eq', strict=True)
                          or (upgrade_to|upper).split('U')[0] is version_compare('5.3.3', operator='eq', strict=True)
                          or (upgrade_to|upper).split('U')[0] is version_compare('5.4.1', operator='eq', strict=True) ) }}"
    upgrade_from_531: "{{ (upgrade_from|upper).split('U')[0] is version_compare('5.3.1', operator='eq', strict=True)
                          and ( (upgrade_to|upper).split('U')[0] is version_compare('5.3.2', operator='eq', strict=True)
                          or (upgrade_to|upper).split('U')[0] is version_compare('5.3.3', operator='eq', strict=True)
                          or (upgrade_to|upper).split('U')[0] is version_compare('5.4.1', operator='eq', strict=True) ) }}"
    upgrade_from_532: "{{ (upgrade_from|upper).split('U')[0] is version_compare('5.3.2', operator='eq', strict=True)
                          and ( (upgrade_to|upper).split('U')[0] is version_compare('5.3.3', operator='eq', strict=True)
                          or (upgrade_to|upper).split('U')[0] is version_compare('5.4.1', operator='eq', strict=True) ) }}"
    upgrade_from_533: "{{ (upgrade_from|upper).split('U')[0] is version_compare('5.3.3', operator='eq', strict=True)
                          and (upgrade_to|upper).split('U')[0] is version_compare('5.4.1', operator='eq', strict=True) }}"
    upgrade_from_60_to_205: "{{ upgrade_from is search('6.0.') and upgrade_to is search('20.5.') }}"

- name: Skip vstat upgrade for versions that do not require upgrade
  set_fact:
    skip_vstat_upgrade: "{{ upgrade_from_521 or upgrade_from_522 or upgrade_from_523 or upgrade_from_531 or upgrade_from_532 or upgrade_from_533 or upgrade_from_60_to_205 }}"
