- block:

  - name: Set Webfilter VM QCOW2 location
    include_role:
      name: common
      tasks_from: find-file.yml
    vars:
      dir_name: "{{ nuage_unzipped_files_dir }}"
      pattern: "Nuage-webfilter-*.qcow2"

  - name: Register Webfilter QCOW2 variables with proper path and image locations for use in other playbooks
    set_fact:
      image_path: "{{ file_path }}"
      image_file_name: "{{ file_name }}"

  - name: Verify Webfilter management gateway is in correct IP range
    include_role:
      name: common
      tasks_from: check-ip-in-range.yml
    vars:
      ip_address: "{{ item.mgmt_gateway }}"
      netaddr: "{{ item.mgmt_ip }}"
      netmask: "{{ item.mgmt_ip_prefix }}"
    with_items: "{{ webfilters }}"

  - name: Create host_vars files for webfilters
    template: src=webfilter.j2 backup=no dest={{ inventory_dir }}/host_vars/{{ item.hostname }}
    with_items: "{{ webfilters }}"

  - name: Verify Webfilter DNS entries exist and hostnames map to their IPs
    include_tasks: check-dns.yml
    with_items: "{{ webfilters }}"
    when: common.dns_server_list | length > 0

  when: webfilters is defined and webfilters|length > 0
