---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - op is defined
      - stack_name is defined
      - stack_install_root_dir is defined

- name: "Performing '{{ op }}' on '{{ stack_name }}'"
  # -y to agree to not ask questions
  # -q to not wait for startups -- this matters because we're not dictating order of startup.
  #    E.g. stroom-auth-service needs the db to finish starting, but what if the db hasn't been asked to start yet?
  command: "chdir={{ stack_dir }}/ ./{{ op }}"
  # Sometimes get a tput error if we don't do this.
  environment:
    TERM: vt100
    # This is needed so our scripts can find the ip command as ansible runs with a
    # different PATH to when you ssh in manually.
    PATH: "{{ ansible_env.PATH}}:/sbin:/usr/sbin"
  register: stack_op
  # This check is a bit more complicated because 'stdout' doesn't always exist on 'stack_op'
  failed_when: "'stdout' in stack_op and 'UNHEALTHY' in stack_op.stdout"

- debug:
    msg: "{{ stack_op.stdout }}"
    verbosity: 2
  when: "'stdout' in stack_op and (op=='info' or op=='status' or op=='health' or op=='logs' or op=='show_config')"
    
- debug:
    msg: "{{ stack_op.stderr }}"
    verbosity: 2
  when: "'stderr' in stack_op"
