- hosts: localhost
  gather_facts: no
  tasks:
    - name: Set fact for backup type
      set_fact:
        backup_type: full

- name: Run VSD Backup
  import_playbook: "vsd_backup.yml"

- name: Run VSC Backup
  import_playbook: "vsc_backup.yml"
