---
- hosts: netconf_managers
  gather_facts: no
  tasks:
   - include_role:
        name: netconf-manager-deploy
        tasks_from: create_netconf_user

- hosts: netconf_managers
  gather_facts: no
  roles:
    - netconf-manager-deploy

- hosts: netconf_managers
  gather_facts: no
  tasks:
   - include_role:
        name: netconf-manager-deploy
        tasks_from: validate_netconf_connected
