---
- name: Run SD-WAN Portal Predeploy
  import_playbook: "sdwan_portal_predeploy.yml"

- name: Run SD-WAN Portal Deploy
  import_playbook: "sdwan_portal_deploy.yml"

- name: Run SD-WAN Portal Postdeploy
  import_playbook: "sdwan_portal_postdeploy.yml"
