---
- name: vsd_predeploy
  import_playbook: "vsd_predeploy.yml"
- name: vsd_deploy
  import_playbook: "vsd_deploy.yml"
- name: vsd_postdeploy
  import_playbook: "vsd_postdeploy.yml"

- name: vsc_predeploy
  import_playbook: "vsc_predeploy.yml"
- name: vsc_deploy
  import_playbook: "vsc_deploy.yml"
- name: vsc_post_deploy
  import_playbook: "vsc_postdeploy.yml"

- name: vstat_predeploy
  import_playbook: "vstat_predeploy.yml"
- name: vstat_deploy
  import_playbook: "vstat_deploy.yml"
- name: vstat_postdeploy
  import_playbook: "vstat_postdeploy.yml"

- name: vsd_vns_deploy
  import_playbook: "vsd_vns_postdeploy.yml"

- name: vnsutil_predeploy
  import_playbook: "vnsutil_predeploy.yml"
- name: vnsutil_deploy
  import_playbook: "vnsutil_deploy.yml"
- name: vnsutil_postdeploy
  import_playbook: "vnsutil_postdeploy.yml"
