---
- hosts: nsgvs
  gather_facts: no
  serial: 1
  pre_tasks:
    - name: Check if NSGVs prereq satisfied for predeploy
      include_role:
        name: common
        tasks_from: check-predeploy-prereq
      vars:
        required_available_disk_space: "{{ nsgv_allocate_size_gb }}"
        disk_space_path: "{{ images_path }}"

    - name: Lets run NSGV predeploy hooks
      include_role:
        name: hooks
        tasks_from: main
      vars:
        - hooks_file_path: "{{ hook }}"
        - hook_location:
          - nsgv_predeploy
          - install_nsgvs
      loop: "{{ hooks | default([]) }}"
      loop_control:
        loop_var: hook
  roles:
    - nsgv-predeploy
