---
- hosts: nuhs
  gather_facts: no
  pre_tasks:
    - name: Check if NUH prereq satisfied for predeploy
      include_role:
        name: common
        tasks_from: check-predeploy-prereq
  roles:
    - nuh-predeploy
