---
- hosts: portals
  gather_facts: no
  pre_tasks:
    - name: Check if SD-WAN Portal prereq satisfied for predeploy
      include_role:
        name: common
        tasks_from: check-predeploy-prereq
  roles:
    - sdwan-portal-predeploy
