---
- hosts: vcins
  gather_facts: no
  pre_tasks:
    - name: Lets run VCIN deploy hooks
      include_role:
        name: hooks
        tasks_from: main
      vars:
        - hooks_file_path: "{{ hook }}"
        - hook_location:
          - vcin_deploy
      loop: "{{ hooks | default([]) }}"
      loop_control:
        loop_var: hook
  roles:
    - vsd-deploy
    - vcin-create-dvs
