---
- hosts: vcins
  gather_facts: no
  pre_tasks:
    - name: Check if VCIN prereq satisfied for predeploy
      include_role:
        name: common
        tasks_from: check-predeploy-prereq
      vars:
        required_available_disk_space: "{{ vcin_allocate_size_gb }}"

    - name: Lets run VCIN predeploy hooks
      include_role:
        name: hooks
        tasks_from: main
      vars:
        - hooks_file_path: "{{ hook }}"
        - hook_location:
          - vcin_predeploy
          - install_vcins
      loop: "{{ hooks | default([]) }}"
      loop_control:
        loop_var: hook
  roles:
    - vsd-predeploy
