---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Prompt for destroy confirmation
      include_role:
        name: common
        tasks_from: prompt-before-destroy
      vars:
        destroy_components_name: VCIN

- hosts: vcins
  gather_facts: no
  pre_tasks:
    - name: Lets run VCIN destroy hooks
      include_role:
        name: hooks
        tasks_from: main
      vars:
        - hooks_file_path: "{{ hook }}"
        - hook_location:
          - vcin_destroy
      loop: "{{ hooks | default([]) }}"
      loop_control:
        loop_var: hook
  roles:
    - vsd-destroy
  vars:
    vm_name: "{{ vmname }}"
