---
- hosts: vnsutils
  gather_facts: no
  pre_tasks:
    - name: Check if VNS Utils prereq satisfied for predeploy
      include_role:
        name: common
        tasks_from: check-predeploy-prereq
    - name: Lets run VNS Utils predeploy hooks
      include_role:
        name: hooks
        tasks_from: main
      vars:
        - hooks_file_path: "{{ hook }}"
        - hook_location:
          - vnsutil_predeploy
          - install_vnsutils
      loop: "{{ hooks | default([]) }}"
      loop_control:
        loop_var: hook
  roles:
    - vnsutil-predeploy
