- hosts: vnsutils
  gather_facts: no
  pre_tasks:
    - name: Lets run VNS Utils postdeploy hooks
      include_role:
        name: hooks
        tasks_from: main
      vars:
        - hooks_file_path: "{{ hook }}"
        - hook_location:
          - vnsutil_postdeploy
      loop: "{{ hooks | default([]) }}"
      loop_control:
        loop_var: hook
  roles:
    - vnsutil-postdeploy
