- hosts: vscs
  gather_facts: no
  pre_tasks:
    - name: Lets run VSC deploy hooks
      include_role:
        name: hooks
        tasks_from: main
      vars:
        - hooks_file_path: "{{ hook }}"
        - hook_location:
          - vsc_deploy
      loop: "{{ hooks | default([]) }}"
      loop_control:
        loop_var: hook
  roles:
    - vsc-deploy
