- name: Run VSC Predeploy
  import_playbook: "vsc_restore_predeploy.yml"

- name: Run VSC Deploy
  import_playbook: "vsc_restore_deploy.yml"

- name: Run VSC Postdeploy
  import_playbook: "vsc_postdeploy.yml"
