---
- hosts: vscs
  gather_facts: no
  serial: 1
  pre_tasks:
    - name: Lets run VSC postdeploy hooks
      include_role:
        name: hooks
        tasks_from: main
      vars:
        - hooks_file_path: "{{ hook }}"
        - hook_location:
          - vsc_postdeploy
      loop: "{{ hooks | default([]) }}"
      loop_control:
        loop_var: hook
  roles:
    - vsc-postdeploy
