---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Prompt for destroy confirmation
      include_role:
        name: common
        tasks_from: prompt-before-destroy
      vars:
        destroy_components_name: VSC

- hosts: vscs
  gather_facts: no
  serial: 1
  pre_tasks:
    - name: Lets run VSC destroy hooks
      include_role:
        name: hooks
        tasks_from: main
      vars:
        - hooks_file_path: "{{ hook }}"
        - hook_location:
          - vsc_destroy
      loop: "{{ hooks | default([]) }}"
      loop_control:
        loop_var: hook
  roles:
    - vsc-destroy
