- hosts: localhost
  gather_facts: no
  tasks:
    - name: Set fact for backup type
      set_fact:
        backup_type: upgrade-vsd
      when: backup_type is not defined

- hosts: vsd_upgrade_sa_node
  gather_facts: no
  remote_user: "{{ vsd_custom_username | default(vsd_default_username) }}"
  become: "{{ 'no' if vsd_custom_username | default(vsd_default_username) == 'root' else 'yes' }}"
  vars:
    ansible_become_pass: "{{ vsd_custom_password | default(vsd_default_password) }}"
  tasks:
    - name: Backup /etc/hosts files on VSD before upgrade
      include_role:
        name: vsd-backup-hostfile
      when: backup_vsd_host_file | default(false)

- hosts: vsd_upgrade_sa_node
  gather_facts: no
  pre_tasks:
    - name: Fail if vsd_migration_iso_path is not defined
      assert:
       that: vsd_migration_iso_path != "MISSING"
       msg: "vsd_migration_iso_path not defined. Please define it and try again."

    - name: Fail if vsd_migration_iso_file_name is not defined
      assert:
       that: vsd_migration_iso_file_name != "MISSING"
       msg: "vsd_migration_iso_file_name not defined. Please define it and try again."

    - name: Set upgrade flag
      set_fact:
        nuage_upgrade: true

    - name: Check if prereq satisfied for upgrade
      include_role:
        name: common
        tasks_from: check-upgrade-prereq
  roles:
    - vsd-dbbackup
