---
- hosts: vsd_upgrade_ha_node2:vsd_upgrade_ha_node3
  serial: 1
  gather_facts: no
  pre_tasks:
    - name: Set vm name, preserve vm and upgrade flag
      set_fact:
        nuage_upgrade: true
    - name: Lets run VSD ha upgrade Shutdown 2 and 3 hooks
      include_role:
        name: hooks
        tasks_from: main
      vars:
        - hooks_file_path: "{{ hook }}"
        - hook_location:
          - vsd_ha_upgrade_shutdown_2_and_3
      loop: "{{ hooks | default([]) }}"
      loop_control:
        loop_var: hook
  vars:
    preserve_vm: true
    vm_name: "{{ vmname }}"
  roles:
    - vsd-services-stop
    - vsd-destroy
