- hosts: vsds
  gather_facts: no
  tasks:
    - name: Run disk performance test
      include_role:
        name: common
        tasks_from: disk-performance-test.yml
      vars:
        disk_performance_file_total_size: "{{ vsd_disk_performance_test_total_file_size }}"
        disk_performance_minimum_threshold: "{{ vsd_disk_performance_test_minimum_threshold }}"
        disk_performance_max_time: "{{ vsd_disk_performance_test_max_time }}"
        ignore_disk_performance_test_errors: "{{ vsd_ignore_disk_performance_test_errors }}"
        disk_performance_username: "{{ vsd_custom_username | default(vsd_default_username) }}"
        disk_performance_password: "{{ vsd_custom_password | default(vsd_default_password) }}"
