---
- hosts: primary_vsds
  gather_facts: no
  tasks:
    - name: Restore /etc/hosts files on VSD after upgrade
      include_role:
        name: vsd-restore-hostfile
      when: backup_vsd_host_file | default(false)

- hosts: primary_vsds
  gather_facts: no
  pre_tasks:
    - name: Set upgrade flag
      set_fact:
        nuage_upgrade: true

    - name: Check if prereq satisfied for upgrade
      include_role:
        name: common
        tasks_from: check-upgrade-prereq
    - name: Lets run VSD upgrade complete hooks
      include_role:
        name: hooks
        tasks_from: main
      vars:
        - hooks_file_path: "{{ hook }}"
        - hook_location:
          - vsd_upgrade_complete
      loop: "{{ hooks | default([]) }}"
      loop_control:
        loop_var: hook
  roles:
    - vsd-upgrade-complete
  post_tasks:
    - name: VSD post install security hardening
      include_role:
        name: vsd-deploy
        tasks_from: vsd_security_hardening.yml
