---
- hosts: primary_vsds
  gather_facts: no
  pre_tasks:
    - name: Lets run VSD deploy hooks
      include_role:
        name: hooks
        tasks_from: main
      vars:
        - hooks_file_path: "{{ hook }}"
        - hook_location:
          - vsd_deploy
          - vsd_ha_upgrade_deploy_1
          - vsd_sa_upgrade_deploy
          - vsd_standby_deploy
      loop: "{{ hooks | default([]) }}"
      loop_control:
        loop_var: hook
  roles:
    - vsd-deploy
  post_tasks:
    - include_role:
        name: vsd-deploy
        tasks_from: vsd_security_hardening.yml
