---
- hosts: vsds
  gather_facts: no
  pre_tasks:
    - name: Set upgrade flag
      set_fact:
        nuage_upgrade: true

    - name: Check if prereq satisfied for upgrade
      include_role:
        name: common
        tasks_from: check-upgrade-prereq
  vars:
    report_filename: vsp_postupgrade_health_report_for_vsd
    vsd_username: "{{ vsd_custom_username | default(vsd_default_username) }}"
    vsd_password: "{{ vsd_custom_password | default(vsd_default_password) }}"
  roles:
    - vsd-health

- hosts: vstats
  gather_facts: no
  serial: 1
  pre_tasks:
    - name: Set upgrade flag
      set_fact:
        nuage_upgrade: true

    - name: Check if prereq satisfied for upgrade
      include_role:
        name: common
        tasks_from: check-upgrade-prereq
  vars:
    report_filename: vstat_postupgrade_health_report
    vstat_username: "{{ vstat_custom_username | default(vstat_default_username) }}"
    vstat_password: "{{ vstat_custom_password | default(vstat_default_password) }}"
  roles:
    - vstat-health
  remote_user: "{{ vstat_default_username }}"

- hosts: vcins
  gather_facts: no
  serial: 1
  pre_tasks:
    - name: Set upgrade flag
      set_fact:
        nuage_upgrade: true

    - name: Check if prereq satisfied for upgrade
      include_role:
        name: common
        tasks_from: check-upgrade-prereq
  vars:
    report_filename: vcin_postupgrade_health_report
    vsd_username: "{{ vsd_custom_username | default(vsd_default_username) }}"
    vsd_password: "{{ vsd_custom_password | default(vsd_default_password) }}"
  roles:
    - vcin-health

- hosts: vscs
  gather_facts: no
  serial: 1
  connection: local
  pre_tasks:
    - name: Set upgrade flag
      set_fact:
        nuage_upgrade: true

    - name: Check if prereq satisfied for upgrade
      include_role:
        name: common
        tasks_from: check-upgrade-prereq
  vars:
    report_filename: vsp_postupgrade_health_report_for_vsc
    vsc_username: "{{ vsc_custom_username | default(vsc_default_username) }}"
    vsc_password: "{{ vsc_custom_password | default(vsc_default_password) }}"
  roles:
    - vsc-health

- hosts: primary_vsds
  gather_facts: no
  pre_tasks:
    - name: Set upgrade flag
      set_fact:
        nuage_upgrade: true

    - name: Check if prereq satisfied for upgrade
      include_role:
        name: common
        tasks_from: check-upgrade-prereq
  vars:
    report_filename: vstat_postupgrade_health_report_for_vsd.txt
  roles:
    - vstat-vsd-health

- hosts: vscs
  gather_facts: no
  pre_tasks:
    - name: Set upgrade flag
      set_fact:
        nuage_upgrade: true

    - name: Check if prereq satisfied for upgrade
      include_role:
        name: common
        tasks_from: check-upgrade-prereq
  vars:
    report_filename: vstat_postupgrade_health_report_for_vsc.txt
    vsc_username: "{{ vsc_custom_username | default(vsc_default_username) }}"
    vsc_password: "{{ vsc_custom_password | default(vsc_default_password) }}"
  roles:
    - vstat-vsc-health

- hosts: vrss
  gather_facts: no
  pre_tasks:
    - name: Set upgrade flag
      set_fact:
        nuage_upgrade: true

    - name: Check if prereq satisfied for upgrade
      include_role:
        name: common
        tasks_from: check-upgrade-prereq
  vars:
    report_filename: vstat_postupgrade_health_report_for_vrs.txt
  roles:
    - vstat-vrs-health
