---
- hosts: vstats
  gather_facts: no
  serial: 1
  vars:
    report_filename: vstat_preupgrade_health_report
    vstat_username: "{{ vstat_custom_username | default(vstat_default_username) }}"
    vstat_password: "{{ vstat_custom_password | default(vstat_default_password) }}"
  roles:
    - vstat-health
  remote_user: "{{ vstat_default_username }}"
