---
- hosts: primary_vsds
  gather_facts: no
  roles:
    - vstat-vsd-health

- hosts: vscs
  gather_facts: no
  roles:
    - vstat-vsc-health
  vars:
    report_filename: vstat_vsc_health_report.txt
    vsc_username: "{{ vsc_custom_username | default(vsc_default_username) }}"
    vsc_password: "{{ vsc_custom_password | default(vsc_default_password) }}"

- hosts: vrss
  gather_facts: no
  roles:
    - vstat-vrs-health

