- hosts: backup_vstats
  gather_facts: no
  pre_tasks:
    - name: Check if VSTATs prereq satisfied for predeploy
      include_role:
        name: common
        tasks_from: check-predeploy-prereq
      vars:
        required_available_disk_space: "{{ vstat_allocate_size_gb }}"
        disk_space_path: "{{ images_path }}"

    - name: Lets run VSTAT predeploy hooks
      include_role:
        name: hooks
        tasks_from: main
      vars:
        - hooks_file_path: "{{ hook }}"
        - hook_location:
          - vstat_predeploy
          - install_vstats
      loop: "{{ hooks | default([]) }}"
      loop_control:
        loop_var: hook
  roles:
    - vstat-predeploy
