---
- hosts: primary_vstats
  gather_facts: no
  pre_tasks:
    - name: Set active flag
      set_fact:
        active: True
        failover: False
  roles:
    - vstat-cluster-failover-failback

- hosts: backup_vstats
  gather_facts: no
  pre_tasks:
    - name: Set active flag
      set_fact:
        active: False
        failover: False
  roles:
    - vstat-cluster-failover-failback
