---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Prompt for destroy confirmation
      include_role:
        name: common
        tasks_from: prompt-before-destroy
      vars:
        destroy_components_name: Webfilter

- hosts: webfilters
  gather_facts: no
  roles:
    - webfilter-destroy
  vars:
    vm_name: "{{ vmname }}"
