---
- name: Create the durable InfluxDB data directory
  file:
    path: "{{ influx_data_dir }}"
    state: directory
    mode: 0755
    recurse: yes

- name: Create the InfluxDB data container
  docker:
    name: influx_data
    image: alpine:3.2
    detach: yes
    state: restarted
    restart_policy: always
    restart_policy_retry: 128
    command: echo 'InfluxDB data container'
    volumes:
      - "{{ influx_data_dir }}:/data"

- name: Run InfluxDB container
  docker:
    name: influx
    image: tutum/influxdb:0.9
    net: host
    detach: yes
    state: restarted
    restart_policy: always
    restart_policy_retry: 128
    volumes_from:
      - influx_data
    env:
      PRE_CREATE_DB: "grafana"

- name: Wait for InfluxDB to come up
  wait_for: port=8086 delay=5 timeout=60
