---

# stroom.conf entries look like 
#
#  stroom.node=node1a
#  stroom.rack=rack1
#  stroom.temp=/tmp/stroom/

- name: "Setting {{ item.key }}={{ item.value }}"
  lineinfile:
    path: "{{ stroom_conf_file }}"
    regexp: '^\s*#?\s*{{ item.key }}=.*'
    line: "{{ item.key }}={{ item.value }}"

