---
- name: Enable ExpandPersistenVolumes on Node
  yedit:
    src: '{{ expand_pv_node_config }}'
    key: kubeletArguments.feature-gates
    value:
    - ExpandPersistentVolumes=true
    state: present
    backup: yes

- import_role:
    name: common
    tasks_from: restart-node.yaml
