- block:

  - name: Bootstrap VSD1 database
    command: /opt/vsd/sysmon/bootPercona.py --force
    when: "'vsd_ha_node1' in groups and inventory_hostname in groups['vsd_ha_node1']"

  - name: Start VSD common processes
    command: monit -g vsd-common start

  - name: Get monit summary for common processes on VSD
    vsd_monit:
      group: vsd-common
    register: proc_list

  - name: Wait for VSD common processes to become running
    monit_waitfor_service:
      name: "{{ proc_list['state'].keys() }}"
      timeout_seconds: 1200
      test_interval_seconds: 30

  - name: Start VSD core processes (ignoring errors)
    command: monit -g vsd-core start
    register: monit_core_output
    ignore_errors: inventory_hostname not in groups['primary_vsds']

  - name: Get monit summary for core processes on VSD
    vsd_monit:
      group: vsd-core
    register: proc_list
    when: monit_core_output.rc == 0

  - name: Wait for VSD core processes to become running
    monit_waitfor_service:
      name: "{{ proc_list['state'].keys() }}"
      timeout_seconds: 1200
      test_interval_seconds: 30
    when: monit_core_output.rc == 0

  - block:

    - name: Start VSD stats processes
      command: monit -g vsd-stats start

    - name: Get monit summary for stats processes on VSD
      vsd_monit:
        group: vsd-stats
      register: proc_list

    - name: Wait for VSD stats processes to become running
      monit_waitfor_service:
        name: "{{ proc_list['state'].keys() }}"
        timeout_seconds: 1200
        test_interval_seconds: 30

    when: groups['vstats'] is defined and groups['vstats'] and inventory_hostname in groups['primary_vsds']

  remote_user: "{{ vsd_custom_username | default(vsd_default_username) }}"
  become: "{{ 'no' if vsd_custom_username | default(vsd_default_username) == 'root' else 'yes' }}"
  vars:
    ansible_become_pass: "{{ vsd_custom_password | default(vsd_default_password) }}"
