- name: Clean known_hosts of VCINs (ignoring errors)
  known_hosts:
    name: "{{ mgmt_ip }}"
    state: absent
  delegate_to: localhost
  no_log: True
  ignore_errors: True

- name: Check VCIN health after deployment
  import_role: name="vcin-health"
  vars:
    report_filename: vcin-postdeploy-health
