---
- name: allow Mythic monitoring hosts through firewall
  template:
    src: mythic-firewalld-zone.xml.j2
    dest: /etc/firewalld/zones/mythic.xml
    mode: 0644
  notify:
    - reload firewalld
  when: base_firewall == 'firewalld'

- name: add mythic repository gpg key
  apt_key:
    url: http://mirror.mythic-beasts.com/mythic/support@mythic-beasts.com.gpg.key

- name: add mythic repository
  apt_repository:
    repo: deb http://mirror.mythic-beasts.com/mythic mythic main
    state: present
    update_cache: yes

- name: allow Mythic monitoring hosts through firewall
  ufw:
    rule: allow
    proto: tcp
    src: "{{ item }}"
    port: 4949
  loop: "{{ base_mythic_firewall_sources }}"
  when: base_firewall == 'ufw'

- name: install Mythic management packages
  package:
    name:
    - mythic-reporter
    state: latest

- name: add Mythic admin ssh key
  authorized_key:
    user: root
    key: "{{ lookup('file', 'ssh/mythic.pub') }}"

- name: ensure hostname
  hostname:
    name: "{{ inventory_hostname }}"
