- name: Run if target_server_type is in the list
  block:

  - name: Display if skipping role
    debug:
      msg:
        - "****************************************************************************"
        - "Skipping {{ ansible_parent_role_names[0] }} because {{ target_server_type }} is not a supported target server type"
        - "****************************************************************************"

  - name: Stop role
    meta: end_play

  when:
    - target_server_list is defined
    - target_server_type not in target_server_list
