- include_role:
    name: check-skip-target-server
  vars:
    - target_server_list: ["kvm", "vcenter", "aws"]

- include_role:
    name: skip-actions
  vars:
    - action: nsgv_predeploy

- name: Set local variable with vmname
  set_fact:
    vm_name: "{{ vmname }}"

- include_role:
    name: check-node-running
  vars:
    do_reachability_checks: False
  when: target_server_type is not match("aws")

- import_tasks: kvm.yml
  when: target_server_type is match("kvm")
  static: no
  tags:
    - nsgv
    - nsgv-predeploy

- import_tasks: aws.yml
  when: target_server_type is match("aws")
  static: no
  tags:
    - nsgv
    - nsgv-predeploy
    - aws

- import_tasks: vcenter.yml
  when: target_server_type is match("vcenter")
  static: no
  tags:
    - nsgv
    - nsgv-predeploy
