- include_role:
    name: check-skip-target-server
  vars:
    - target_server_list: ["kvm", "vcenter", "aws", "openstack"]

- import_tasks: kvm.yml
  when: target_server_type is match("kvm")
  tags:
    - vstat
    - vstat-destroy

- import_tasks: openstack.yml
  when: target_server_type is match("openstack")
  tags:
    - vstat
    - openstack
    - vstat-destroy

- import_tasks: vcenter.yml
  when: target_server_type is match("vcenter")
  tags:
    - vstat
    - vstat-destroy

- import_tasks: aws.yml
  when: target_server_type is match("aws")
  tags:
    - vstat
    - vstat-destroy
