- block:

  - name: Destroy VSTAT VM
    virt:
      name: "{{ inventory_hostname }}"
      state: destroyed
      uri: qemu:///system

  - name: Undefine VSTAT VM
    virt:
      name: "{{ inventory_hostname }}"
      command: undefine
      uri: qemu:///system

  delegate_to: "{{ target_server }}"
  remote_user: "{{ target_server_username }}"
  become: "{{ 'no' if target_server_username == 'root' else 'yes' }}"
