- hosts: localhost
  tasks:
  
    - name: Load Storage System Vars
      include_vars: 'properties/storage_system_properties.yml'
      
    - name: Load QoS Vars
      include_vars: 'properties/qos_properties.yml'
      
    - name: Delete QoS
      hpe3par_qos:
        storage_system_ip="{{ storage_system_ip }}"
        storage_system_username="{{ storage_system_username }}"
        storage_system_password="{{ storage_system_password }}"
        state=absent 
        qos_target_name='Chef_TK_Volume_Set'
        type='vvset'
        
    - name: Delete VVSET
      hpe3par_volumeset: 
        storage_system_ip="{{ storage_system_ip }}"
        storage_system_username="{{ storage_system_username }}"
        storage_system_password="{{ storage_system_password }}"
        state=absent 
        volumeset_name="Chef_TK_Volume_Set"
        
    - name: Delete Flash Cache
      hpe3par_flash_cache:
        storage_system_ip="{{ storage_system_ip }}"
        storage_system_username="{{ storage_system_username }}"
        storage_system_password="{{ storage_system_password }}"
        state=absent 