- hosts: localhost
  tasks:
  
    - name: Load Storage System Vars
      include_vars: 'properties/storage_system_properties.yml'
      
    - name: Load Host Vars
      include_vars: 'properties/host_properties.yml'
      
    - name: Load Hostset Vars
      include_vars: 'properties/hostset_properties.yml'
           
    - name: Load Volume Vars
      include_vars: 'properties/volume_properties.yml'
      
    - name: Load Volume Vars
      include_vars: 'properties/volumeset_properties.yml'  
      
    - name: Load VLUN Vars
      include_vars: 'properties/vlun_properties.yml'            
            
    - name: Create host, host-sets, volume and volume-sets
      import_tasks: setup_vlun.yml       
        
    - name: Create VLUN 
      hpe3par_vlun: 
        storage_system_ip="{{ storage_system_ip }}"
        storage_system_username="{{ storage_system_username }}"
        storage_system_password="{{ storage_system_password }}"
        state=export_volumeset_to_hostset 
        volume_set_name="{{ volumeset_name }}"
        host_set_name="{{ hostset_name }}"
        lunid="{{ lunid }}" 
        autolun="{{ autolun }}" 
        
    - name: Delete VLUN 
      hpe3par_vlun: 
        storage_system_ip="{{ storage_system_ip }}"
        storage_system_username="{{ storage_system_username }}"
        storage_system_password="{{ storage_system_password }}"
        state=unexport_volumeset_to_hostset 
        volume_set_name="{{ volumeset_name }}"
        host_set_name="{{ hostset_name }}" 
        lunid="{{ lunid }}"       
     
    - name: Delete host, host-sets, volume and volume-sets
      import_tasks: cleanup_vlun.yml
