---
- include: Debian.yml
  when: ansible_os_family == "Debian"
  tags: turn

- include: RedHat.yml
  when: ansible_os_family == "RedHat"
  tags: turn

- name: Upload SSL certificates
  copy: >
    src=../../../certs/{{ item }}
    dest=/etc/ssl/{{ item }}
    mode=0644
  with_items:
    - "{{ certfile }}"
    - "{{ keyfile }}"
  tags: turn

- name: Provide coturn configuration file
  template: >
    src=turnserver.conf
    dest=/etc/turnserver.conf
    mode=0644
  notify:
    - Restart coturn service
  tags: turn
